# Generated by Django 4.2.2 on 2023-10-25 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(max_length=150, verbose_name='especialidad')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(max_length=150, verbose_name='Plan')),
            ],
        ),
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='nombre')),
                ('apellido', models.CharField(max_length=30, verbose_name='apellido')),
                ('email', models.EmailField(max_length=150, verbose_name='email')),
                ('dni', models.IntegerField(unique=True, verbose_name='dni')),
                ('matricula', models.CharField(max_length=100, verbose_name='matricula')),
                ('cuit', models.CharField(max_length=100, verbose_name='cuit')),
                ('especialidad', models.CharField(max_length=150, verbose_name='especialidad')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Afiliado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='nombre')),
                ('apellido', models.CharField(max_length=30, verbose_name='apellido')),
                ('email', models.EmailField(max_length=150, verbose_name='email')),
                ('dni', models.IntegerField(unique=True, verbose_name='dni')),
                ('numeroAfiliado', models.CharField(max_length=100, verbose_name='numeroAfiliado')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_principal.plan')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
