# Generated by Django 4.2.2 on 2023-10-23 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Afiliado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='nombre')),
                ('apellido', models.CharField(max_length=30, verbose_name='apellido')),
                ('email', models.EmailField(max_length=150, verbose_name='email')),
                ('dni', models.IntegerField(unique=True, verbose_name='dni')),
                ('numeroAfiliado', models.CharField(max_length=100, verbose_name='numeroAfiliado')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='nombre')),
                ('apellido', models.CharField(max_length=30, verbose_name='apellido')),
                ('email', models.EmailField(max_length=150, verbose_name='email')),
                ('dni', models.IntegerField(unique=True, verbose_name='dni')),
                ('matricula', models.CharField(max_length=100, verbose_name='Matrícula')),
                ('especialidad', models.CharField(max_length=100, verbose_name='Especialidad')),
                ('cuit', models.CharField(max_length=100, verbose_name='CUIT')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
