# Generated by Django 4.2.2 on 2023-11-03 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_principal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialidadesprofesionales',
            name='profesionales',
            field=models.ManyToManyField(related_name='nombre_profesional', to='app_principal.profesional'),
        ),
        migrations.CreateModel(
            name='CrearTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_principal.especialidades')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_principal.profesional')),
            ],
        ),
    ]
