# Generated by Django 4.2.2 on 2023-11-08 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_principal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='especialidadesprofesionales',
            name='profesionales',
        ),
        migrations.AddField(
            model_name='especialidadesprofesionales',
            name='profesional',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app_principal.profesional'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profesional',
            name='especialidades',
            field=models.ManyToManyField(related_name='profesionales', through='app_principal.EspecialidadesProfesionales', to='app_principal.especialidades'),
        ),
    ]
