# Generated by Django 4.2.2 on 2023-10-24 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_principal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turnos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_principal.afiliado')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_principal.profesional')),
            ],
        ),
        migrations.CreateModel(
            name='Especialidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.TextField(max_length=150, verbose_name='Especialidad')),
                ('profesionales', models.ManyToManyField(related_name='nombre_completo', to='app_principal.profesional')),
            ],
        ),
    ]
