# Generated by Django 4.2.5 on 2023-10-24 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_principal', '0002_turnos_especialidades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turnos',
            name='profesional',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_principal.profesional'),
        ),
    ]
