# Generated by Django 4.2.2 on 2023-10-22 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_principal', '0002_afiliado_profesional_delete_persona'),
    ]

    operations = [
        migrations.RenameField(
            model_name='afiliado',
            old_name='numeroAfilado',
            new_name='numeroAfiliado',
        ),
    ]
