# Generated by Django 4.2.2 on 2023-11-08 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_principal', '0002_remove_especialidadesprofesionales_profesionales_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='especialidadesprofesionales',
            name='profesional',
        ),
        migrations.RemoveField(
            model_name='profesional',
            name='especialidades',
        ),
        migrations.AddField(
            model_name='especialidadesprofesionales',
            name='profesionales',
            field=models.ManyToManyField(related_name='nombre_profesional', to='app_principal.profesional'),
        ),
        migrations.RemoveField(
            model_name='especialidadesprofesionales',
            name='especialidad',
        ),
        migrations.AddField(
            model_name='especialidadesprofesionales',
            name='especialidad',
            field=models.ManyToManyField(related_name='especialidades', to='app_principal.especialidades'),
        ),
    ]
