# Generated by Django 4.2.2 on 2023-10-24 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_principal', '0003_alter_turnos_profesional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesional',
            name='especialidad',
            field=models.TextField(max_length=150, verbose_name='Especialidad'),
        ),
        migrations.AlterField(
            model_name='turnos',
            name='profesional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_principal.profesional'),
        ),
    ]
